---

- name: "SAP: File Permissions"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  loop:
    - {node_tier: 'hdb', path: '/hana', mode: '0755', owner: 'root', group: 'root', state: 'directory'}
    - {node_tier: 'pas', path: '/sapmnt', mode: '0755', owner: 'root', group: 'sapsys', state: 'directory'}
    - {node_tier: 'app', path: '/sapmnt', mode: '0755', owner: 'root', group: 'sapsys', state: 'directory'}
  when: item.tier == "all" or
        item.tier == node_tier

...


# - name: "Ensure /usr/sap permissions are correct"
#   file:
#      path: "/usr/sap"
#      state: directory
#      mode: "0777"
#      group: "sapsys"

# - name: "Ensure /sapmnt permissions are correct"
#   file:
#      path: "/sapmnt"
#      state: directory
#      mode: "0777"

# - name: Ensure a temporary directory for executing the installation exists
#   file:
#     path: "/tmp/{{ bom_base_name }}"
#     state: directory
#     owner: root
#     group: sapinst
#     mode: "0777"
