name: Ansible Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          ansible==2.9
          ansible-lint
    - run: "ansible-lint -x role-name,line-length,comments,comments-indentation,empty-string-compare -v --force-color ${{ github.workspace }}/deploy/ansible/*role* --exclude=${{ github.workspace }}/deploy/ansible/XXroles --exclude=${{ github.workspace }}/deploy/ansible/vars/"
